class ExecutionConfig:
    """
    Stores execution-time configuration.

    These are values that are known before execution starts and
    should never be generated by AI.

    Examples

    - Username
    - Password
    - Base URL
    - Tenant
    - Environment
    """

    def __init__(self):

        self._values = {
            "username": "engineer",
            "password": "partsonly",
        }

    # --------------------------------------------------
    # Lookup
    # --------------------------------------------------

    def get(
        self,
        field_name: str,
    ):

        return self._values.get(
            field_name.lower(),
        )

    # --------------------------------------------------
    # Update
    # --------------------------------------------------

    def set(
        self,
        field_name: str,
        value,
    ):

        self._values[field_name.lower()] = value